Run pipelinerun and taskrun checks after pod checks
Signed-off-by: Sneha Jaiswal <sneha.jaiswal22@ibm.com>

diff --git a/pipeline.yaml b/pipeline.yaml
--- a/pipeline.yaml
+++ b/pipeline.yaml
@@ -135,26 +135,6 @@ spec:
             echo "waiting for test pods to complete..."
 
             for (( n = 1; n <= $(($(params.timelimit))); n++ )) ; do
-              # gets status of pipelineruns, if any
-              pipelineruns=$(oc get pipelinerun -n $(params.namespace) -o jsonpath='{.items[*].status.conditions[0].status}')
-              if [[ $pipelineruns =~ "False" ]]; then
-                echo "At least one PipelineRun failed!"
-                echo "Printing reason and message..."
-                oc get pipelinerun -n $(params.namespace) -o jsonpath='{range .items[*]}{.status.conditions[0].reason}{"\n"}{end}'
-                oc get pipelinerun -n $(params.namespace) -o jsonpath='{range .items[*]}{.status.conditions[0].message}{"\n"}{end}'
-                exit 1
-              fi
-
-              # gets status of taskruns, if any
-              taskruns=$(oc get taskrun -n $(params.namespace) -o jsonpath='{.items[*].status.conditions[0].status}')
-              if [[ $taskruns =~ "False" ]]; then
-                echo "At least one TaskRun failed!"
-                echo "Printing reason and message..."
-                oc get taskrun -n $(params.namespace) -o jsonpath='{range .items[*]}{.status.conditions[0].reason}{"\n"}{end}'
-                oc get taskrun -n $(params.namespace) -o jsonpath='{range .items[*]}{.status.conditions[0].message}{"\n"}{end}'
-                exit 1
-              fi
-
               # gets status of current pods as array of strings
               pods=()
               phases=()
@@ -176,6 +156,26 @@ spec:
                       COMPLETION=0
                   fi
               done
+
+              # gets status of pipelineruns, if any
+              pipelineruns=$(oc get pipelinerun -n $(params.namespace) -o jsonpath='{.items[*].status.conditions[0].status}')
+              if [[ $pipelineruns =~ "False" ]]; then
+                echo "At least one PipelineRun failed!"
+                echo "Printing reason and message..."
+                oc get pipelinerun -n $(params.namespace) -o jsonpath='{range .items[*]}{.status.conditions[0].reason}{"\n"}{end}'
+                oc get pipelinerun -n $(params.namespace) -o jsonpath='{range .items[*]}{.status.conditions[0].message}{"\n"}{end}'
+                exit 1
+              fi
+
+              # gets status of taskruns, if any
+              taskruns=$(oc get taskrun -n $(params.namespace) -o jsonpath='{.items[*].status.conditions[0].status}')
+              if [[ $taskruns =~ "False" ]]; then
+                echo "At least one TaskRun failed!"
+                echo "Printing reason and message..."
+                oc get taskrun -n $(params.namespace) -o jsonpath='{range .items[*]}{.status.conditions[0].reason}{"\n"}{end}'
+                oc get taskrun -n $(params.namespace) -o jsonpath='{range .items[*]}{.status.conditions[0].message}{"\n"}{end}'
+                exit 1
+              fi
               
               if [ "$COMPLETION" == '1' ]; then
                   echo "All test pods succeeded!"
